spring:
  application:
    name: apigateway
  config:
    import: optional:configserver:http://localhost:8889
#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: trace

server:
  port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


#spring:
#  application:
#    name: apigateway
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/products/**
#        - id: user-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/users/**
#        - id: order-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/orders/**, /api/cart/**
#
#server:
#  port: 8181


#http://localhost:8181/eureka/main  --> eureka on api gateway
